### ISSUE TITLE
Better Description suggestion

### ISSUE THREAD

**Issue by CPBen** [moznion/Plack-Request-WithEncoding#2]
I submitted this module to be ported into OpenBSD.
I was asked to create a more informative one for the DESCR file which shows up for the built packages. This one points out when someone might want to use this module in particular.

Plack::Request::WithEncoding is a subclass of Plack::Request that
supports encoded requests.  It overrides many Plack::Request
attributes to return decoded values.
This feature allows a single application to seamlessly handle a wide
variety of different language code sets.
Applications that must be able to handle many different translations
at once will find this extension able to quickly solve that problem.

**Comment by moznion** [comment]
Thank you for your suggestion. I'll consider that.

**Comment by moznion** [comment]
I've updated the wording of this issue: https://github.com/moznion/Plack-Request-WithEncoding/commit/33a11dd97144af068bbe3e7cee101d487898fd36

Thank you for your suggestion, @CPBen++

**Comment by moznion** [comment]
I've published the new version v0.13 that contains this change for documentation: https://metacpan.org/pod/release/MOZNION/Plack-Request-WithEncoding-0.13/lib/Plack/Request/WithEncoding.pm
